- python/hopsworks/client/auth.py
- python/tests/hopsworks/test_login.py
Addition to what is written in [#184](https://github.com/logicalclocks/hopsworks-api/issues/184)
The current implementation of the authorization header results in an edge case where, when the resulting header is deemed invalid from the underlying HTTP library (urllib3), a value error is thrown, which is simply printed. This includes the content of the authorization header (the API key).
By simply stripping any leading or trailing white spaces (which include newlines), this should get rid of the error.
I can also not think of any edge cases where stripping the API key might lead to problems, since only whitespace leading or trailing the actual API key will be removed.
One could make the case that the strip is unnecessary for the bearer token, but my argument for keeping it is that it
1. …
> added testcase for newline in api key

- python/hopsworks/__init__.py
- python/hopsworks/client/__init__.py
- python/hopsworks/connection.py
Cleanup client irrespective of whether connection was set properly
> [FSTORE-1320] Fix hopsworks.login second attempt not taking parameters into account

- CONTRIBUTING.md
- docs/CONTRIBUTING.md
- python/hopsworks/__init__.py
- python/hopsworks/core/execution_api.py
- python/hopsworks/execution.py
- python/hopsworks/project.py
…store + stop execution method
> [FSTORE-1281] Add method to stop execution + type hinting login+get_feature_store

- python/hsfs/core/vector_server.py
- python/hsfs/feature_view.py
- python/hsfs/hopsworks_udf.py
- python/hsfs/training_dataset_feature.py
This PR fixes some bugs introduced from https://github.com/logicalclocks/feature-store-api/pull/1371
** Changes Done ** 
1. Updated check while to set `output_column_names` for `hopsworks_udf` so that it does not set the `output_column_names` if it is empty which can be a possibility when the udf is not attached to a feature view or feature group. Output column names can only be generated when udf is known to be On-Demand (attached to feature group) or Model Dependent (attached to feature view).
2. Changed argument name `transformed` into `transform` as per review comments obtained here (https://github.com/logicalclocks/logicalclocks.github.io/pull/397).
3. Updated vector to have variable `_on_demand_feature_vector_col_name` which store the untransformed and on demand features as a list. …
> [FSTORE-1411-APPEND] On-Demand Transformation Functions

- python/hsfs/hopsworks_udf.py
This PR fixes a bug introduced by the PR https://github.com/logicalclocks/feature-store-api/pull/1371
Issue - Transformation function read from feature store directly using the `get_transformation_function` causing a exception in the backend because the column  `transformation_function_argument_names` is not set.
Root Cause - Issue caused by `transformation_function_argument_names` not being set in `from_response_json`. This cause transformation function read from the backend to not the `transformation_function_argument_names` which in turn causes the DTO to not have it.
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1411-APPEND] On-Demand Transformations

- python/hsfs/engine/python.py
This PR fixes an issue introduced in PR https://github.com/logicalclocks/feature-store-api/pull/1308
Issue : 
Null values were created in the transformed train-test split when the built-in transformation function `label encoder` was used in the feature view.
Root Cause : 
The built in transformation function `label_encoder` returned a newly created pandas Series instead of returning the modified input. The input dataFrame provided to the transformation function contains shuffled indexes when a train-test split is being created. Since a new pandas Series was created within the transformation function the indexes did not match with the input dataFrame. Hence introducing null values when concatenating them together.
Fix Done : 
Reset the index of both the input dataFrame and the output …
> [APPEND][FSTORE-1285] Model Dependent Transformations

- python/hsfs/engine/python.py
- python/hsfs/engine/spark.py
This PR fixes a load test for external fraud batch data validation.
**Issue**:
Inserting into external feature groups causes [AttributeError: `FeatureGroup` object has no attribute `transformation_functions`. If you are trying to access a feature, fall back on using the `get_feature` method.](https://jenkins.hops.works/job/freestyle_report_kube_loadtests/19/testReport/workflows.feature_store.python_driver/test_external_fraud_batch_data_validation/test_workflow/)
**Root Cause**: 
Inserting into feature group currently applies transformations function, but external feature groups do not support on-demand transformations.
**Fix Done**: 
Prevent application of transformation function during insert in external feature groups. 
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1494 …
> [FSTORE-1484] External Fraud batch Validation workflow test failing with `transformation_functions` not found in feature group

- python/hsfs/core/monitoring_window_config_engine.py
- python/hsfs/engine/python.py
This PR fixes a load tests : [recreate_training_data](https://jenkins.hops.works/job/freestyle_report_kube_loadtests/34/testReport/workflows.feature_store.python_driver/test_recreate_training_data/test_training_data/) and [feature_monitoring](https://jenkins.hops.works/job/freestyle_report_kube_loadtests/34/testReport/workflows.feature_store.pyspark_driver/test_feature_monitoring/test_pyspark_feature_monitoring/)
**Issue**:
1. Creating training dataset without any transformations with arrow-flight enable causes 'TrainingDataset' object has no attribute 'transformation_functions'.
2. Running feature monitoring  causes 'TrainingDataset' object has no attribute 'transformation_functions'.
**Root Cause**:
1. Transformation functions were implemented earlier as part of `TrainingDataset` object …
> [FSTORE-1499] Recreate training dataset and feature monitoring load test failing with `transformation_functions` not found in feature group

- python/hsml/core/serving_api.py
Deployment predict failed because the url is not correct
```
RestAPIError: Metadata operation error: (url: http://162.19.236.243:32080/hopsworks-api/api/v1/models/irisdeployed:predict). Server response: 
HTTP code: 404, HTTP reason: Not Found, body: b'{"detail":"Not Found"}', error code: , error msg: , user msg: 
```
Change:
the correct url is `http://162.19.236.243:32080/v1/models/irisdeployed:predict` which does not include the base url.
JIRA Issue: -
Related PRs: -
```
```
> Fix istio client url

- python/hopsworks_common/job.py
This PR fixes an issue in which `create_train_test_split` infinitely waits in the python client.
**Root Cause**
Issue caused because the while loop in `_wait_for_job` never exits since `_job_api.last_execution` will always provide a value for any already executed job.
**Fix Done**
Removed the while loop in `_wait_for_job` this is unnecessary because the blocking wait is already being performed in inside `_execution_engine.wait_until_finished`
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1506][APPEND] Minor fixes for loadtests

- .github/workflows/python.yml
- python/hsfs/hopsworks_udf.py
- python/pyproject.toml
- python/tests/test_helpers/transformation_test_helper.py
- python/tests/test_hopswork_udf.py
This PR fixes the issue of improper code generated when transformation functions are defined in the format:
```
def test_function_transformation_statistics_as_default_multiple_line(arg1: pd.Series,
arg2, 
statistics=TransformationStatistics("arg1", "arg2")
):
pass
```
**Root Cause**: 
The end line of a signature was detected by checking if the line ends with `)`. However in the example given above the `TransformationStatistics` is declared with the function signature causing `)` to be present at a line before the signature actually ends.
**Fix Done**:
Use a regex to check for the function signature end. 
- The regex used is `r"\)\s*(->.*)?\s*:$"`
- The expression check if a `:` is  present after `)` and if the line ends with a `:`. It also matches if a `->` and the type is present in …
> [FSTORE-1411][APPEND] On-Demand Transformations

- utils/java/src/main/java/com/logicalclocks/utils/MainClass.java
- utils/python/hsfs_utils.py
JIRA Issue: -
Related PRs: -
```
```
> [HWORKS-1565] Make sure the spark program exits after completion 

- python/hsfs/core/feature_view_engine.py
- python/hsfs/feature_view.py
- python/hsfs/training_dataset_feature.py
- python/tests/core/test_feature_view_engine.py
This PR adds support for adding transformation function to labels in the feature view.
**Changes done**
- Added property `transformation_labels` which provide names of labels after transformation functions have been applied to it.
- Added function `get_training_dataset_schema` which provide the schema of the features for a specific training dataset version.  Training dataset schema can only be generated after creation of a training dataset because the schema can vary based on training dataset statistics if the transformation `one_hot_encoder` is applied.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-471
Related PRs: -
```
```
> [FSTORE-471] Allow transformation functions for label features

- python/hsfs/core/feature_view_engine.py
- python/hsfs/feature_view.py
- python/tests/core/test_feature_view_engine.py
This PR fixes a bug introduces as part of PR https://github.com/logicalclocks/hopsworks-api/pull/296
**Issue:**
Training dataset materialization PySpark Job failing with the error. "No statistics available for initializing transformation functions. Training data can be created by `feature_view.create_training_data` or `feature_view.training_data`".
**Root Cause:**
- While materializing training dataset using PySpark Jobs, the metadata of the training dataset are created in the Python Client. Then using `hsfs_utils` the training dataset Spark Job is triggered. 
- Since the meta data is already created in the Python Client the spark Job calls get `_get_training_dataset_metadata` function which in turn calls `get_training_dataset_schema` function. 
- The `get_training_dataset_schema` …
> [FSTORE-471][APPEND]  Allow transformation functions for label features

- python/hsfs/core/arrow_flight_client.py
This PR fixes a issue in which training dataset materialization using Arrowflight was throwing a Permission Error
**Root Cause**
When trying to creating training dataset using Arrowflight a request is send from the python client to arrowflight that contains the feature store name along with other parameters. The feature store name is by default cast to into lower case letters before sending. 
Arrowflight then uses this feature store name to construct the path required to access the training dataset directory but the constructed path is incorrect because the feature store name has been casted to lower cases. 
So Arrowflight requests lock access for the parent directories (/Projectto create the provided path which gets rejected because it should not be able to access the directory.
**Fix …
> [FSTORE-1530] Training Data Materialization using Arrowflight fails with PermissionError when a workflow test run as a Kubernetes Job

- java/pom.xml
- python/hopsworks/version.py
- python/pyproject.toml
- requirements-docs.txt
This PR fixes an issue in which hopworks is not importable because Polars throws a `Illegal instruction (core dumped)` due to AVX instructions being unavailable.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1533
Related PRs: 
https://github.com/logicalclocks/feature-store-api/pull/1379
https://github.com/logicalclocks/loadtest/pull/454
```
```
> [FSTORE-1533] Importing hopsworks fails due to core dump while importing polars

- python/hsfs/feature_group.py
- python/tests/test_feature_group.py
This PR adds a new function `select_features` to a feature view that selects all the features in the feature group excluding the event time and the primary key.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1488
Related PRs: -
```
```
> [FSTORE-1488] Create `select_features` function that return all features in the feature group excluding event_time and primary_key

- python/hsfs/core/online_store_sql_engine.py
- python/hsfs/core/util_sql.py
This PR aims to solve the issue caused by get_feature_vector locking the mysql table of the online store. By setting autocommit to false as default, connection were defaulting to repeated_read causing a lock on the underlying table, preventing deletion of the table and therefore the corresponding Feature Group.
This PR reverts the temporary hack closing connections on every call to unblock downstream tests.
This PR is intended to be minimal in scope to limit breaking existing code path. Further cleanup will be forthcoming
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1540] Enforce releasing lock on mysql table after reading feature values from online store

- python/hopsworks/__init__.py
JIRA Issue: -
Related PRs: -
```
```
> [HWORKS-1620] Set hostname verification off by default in python client

- utils/java/src/main/java/com/logicalclocks/utils/MainClass.java
- utils/python/hsfs_utils.py
This PR fixes the issue in which exceptions are lost if a spark Job Fails.
Root Cause:
PR https://github.com/logicalclocks/hopsworks-api/pull/275 added a `system.exit(1)` to kill the Kubernetes pod in case of spark Job Failure. However this causes the exception logs to be lost since they are not re-raised after the finally block.
https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions
Fix Done: 
As a temporary fix the exceptions before calling System.exit(1). Jira ticket has been created for further investigation of the need for a System.exit
JIRA Issue: -
Related PRs: -
```
```
> [HWORKS-1565][APPEND] Make sure the spark program exits after completion

- python/hsfs/feature_store.py
- python/hsfs/storage_connector.py
JIRA Issue: -
Related PRs: -
```
```
>  [FSTORE-1537][APPEND] Managed feature group doc fix

- python/hsfs/core/vector_server.py
- python/hsfs/engine/python.py
- python/hsfs/engine/spark.py
- python/hsfs/hopsworks_udf.py
- python/hsfs/transformation_function.py
- python/tests/engine/test_python.py
- python/tests/engine/test_python_spark_transformation_functions.py
- python/tests/engine/test_spark.py
- python/tests/fixtures/feature_group_fixtures.json
- python/tests/fixtures/feature_view_fixtures.json
- python/tests/fixtures/training_dataset_feature_fixtures.json
- python/tests/fixtures/transformation_function_fixtures.json
- python/tests/test_hopswork_udf.py
This PR adds support for 
- Python UDF's in transformation functions as discussed in design document (https://hopsworks.atlassian.net/wiki/spaces/FST/pages/555221020/Python+UDF+and+Pandas+UDF+s+in+Transformation+Functions).
- Adds support for overwriting features with transformed features for one-to-one and many-to-one transformations. A feature would be overwritten with the transformed feature if the transformation function name matches any of the features passed as input to the transformation function. This is only supported for transformation function returning one transformed features.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1507
Related PRs: 
https://github.com/logicalclocks/hopsworks-ee/pull/1950 …
> [FSTORE-1507] Python UDF's

- python/hopsworks_common/connection.py
At the moment the last shown error is something like “client doesn’t have `_project_id`“, and to find the real cause of the error one has to scroll up to a REST error. The REST error should be shown as the last error instead (we should fail earlier).
JIRA Issue: FSTORE-1567
Related PRs: -
```
```
> [FSTORE-1567] Fix login error messages

- python/hopsworks/connection.py
JIRA Issue: -
Related PRs: -
```
```
> Add finalizer to Connection

- python/hsfs/builtin_transformations.py
- python/hsfs/engine/python.py
This PR fixes the `build_in_transformation_functions` load test. 
**Issue:**
- The test was failing with an assertion error when validating values of `train_test_split` because of `Null` values being re turned when the `label_encoder` transformation function was being used.
- Label Encoder and One-hot encoder were decided to be left as `pandas_udf` since they were too complex to be implemented as python functions. However, the execution mode of built-in function isn the `hopsworks-api` was not set correctly. 
**Root Cause:**
When a train test split is created using a random split the training and test dataset created would have their index shuffled. When an input Series is provided to the transformation function it would have the same index as the train/test DataFrame. 
However the …
> [FSTORE-1576] Fix built-in transformation functions workflow test and Parallelize transformation function tests

- python/hsfs/core/vector_server.py
- python/hsfs/feature_view.py
This PR fixes an issue in which dummy data needs to be provided using `entires` to the function `get_feature_vector` while retrieving feature vectors from a feature view with only on-demand features. 
**Issue:**
User have to always provide `entires` in the function `get_feature_vector` when reading feature vectors from a feature view. 
In the use case in which a feature view contains only on-demand features,  all features are computed while retrieving feature vectors using provided request parameter. Hence `entries` is not a mandatory parameter.
**Fix Done:**
Made `entries` into an optional parameter in cases where the feature view contains only on-demand features.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1606
Related PRs: …
> [FSTORE-1606] Allow ´entries´ to be None while retrieving feature vectors from a feature view with only on-demand features

- locust_benchmark/create_feature_group.py
Creates the locust feature view when creating the feature group. This will prevent the workers to get a race condition creating it.
> [HWORKS-1839] Create fv in master code

- python/hopsworks/__init__.py
- python/hopsworks_common/client/external.py
- python/hopsworks_common/connection.py
- python/hsfs/engine/__init__.py
- python/hsfs/engine/spark_no_metastore.py
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1626] Spark client without hopsfs

- java/pom.xml
- java/spark/pom.xml
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1628] Update deequ for spark 3.5 support

- python/hsfs/feature_group.py
- python/hsfs/feature_view.py
- python/hsfs/training_dataset.py
JIRA Issue: -
Related PRs: -
```
```
> Fix link to job configuration documentation

- python/hopsworks_common/decorators.py
- python/hsfs/core/kafka_engine.py
- python/tests/core/test_kafka_engine.py
JIRA Issue: -
Related PRs: -
```
```
> Fix error message when kafka is not installed

- python/hopsworks_common/core/dataset_api.py
- python/hopsworks_common/kafka_topic.py
- python/hopsworks_common/util.py
- python/tests/test_kafka_topic.py
JIRA Issue: [FSTORE-1522](https://hopsworks.atlassian.net/browse/FSTORE-1522)
[FSTORE-1522]: https://hopsworks.atlassian.net/browse/FSTORE-1522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FSTORE-1522] [APPEND] Fix hsml deduplication

- docs/js/dropdown.js
- docs/js/inject-api-links.js
- mkdocs.yml
The headers in the main documentation are different than the headers in the Hopsworks API documentation. In particular:
- Setup and Installation and Administration have been merged into: Setup and Administration
- Python API has been renamed to Hopsworks API
JIRA Issue: -
Related PRs: -
```
```
> Fix doc headers in the Hopsworks API documentation

- python/hopsworks_common/connection.py
JIRA Issue: [FSTORE-1645](https://hopsworks.atlassian.net/browse/FSTORE-1645)
[FSTORE-1645]: https://hopsworks.atlassian.net/browse/FSTORE-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FSTORE-1645] Catch HSML initialization permission-related errors in login

- java/hsfs/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
- java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestStorageConnector.java
- python/hsfs/storage_connector.py
- python/tests/test_storage_connector.py
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1605] Add “global” path field in the storage connector

- python/hsfs/core/vector_server.py
- python/hsfs/feature_view.py
This PR cherry picks the fix done in PR https://github.com/logicalclocks/hopsworks-api/pull/405 to the 4.1 branch
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1606
Priority for Review: 
Related PRs: 
```
```
> [FSTORE-1606][4.1] Allow ´entries´ to be None while retrieving feature vectors from a feature view with only on-demand features

- python/hsfs/core/vector_server.py
- python/hsfs/feature_view.py
This PR introduces a **breaking change**.
It changes the behaviour of `get_feature_vector` so as a disconnect, on-demand features from the `transform` argument. 
In the updated behaviour when:
- `transform=True` and `on_demand_feature=True/False` -  Return the complete transfomed feature vector with on-demand features and model-dependent features.
- `transform=False` and `on_demand_feature=True` - Return feature vector with on-demand features but no model-dependent transformations applied.
- `transform=False` and `on_demand_feature=False` - Return untransformed feature vector without on-demand features or model-dependent transformations applied.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1682
Related PRs: -
**Checklist …
> [FSTORE-1682] Change default behaviour of get_feature_vector to return on-demand features by default

- python/hopsworks/__init__.py
JIRA Issue: -
Related PRs: -
```
```
> [HWORKS-2037] Always default to python engine in the Python kernel

- .github/workflows/java.yml
- .github/workflows/mkdocs-main.yml
- .github/workflows/mkdocs-release.yml
JIRA Issue: -
Related PRs: -
```
```
> [HWORKS-2055] hopsworks-api uses deprecated actions/cache: v2 which fails the PR tests

- python/hopsworks_common/util.py
- python/hsfs/core/online_store_sql_engine.py
This PR cherry picks changes done in PR https://github.com/logicalclocks/hopsworks-api/pull/484 to the 4.2 branch
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1656
Related PRs: -
```
```
> [FSTORE-1656][4.2] Fetching feature vectors in the predictor file of a deployment fails with event loop is already running error

- python/hopsworks_common/core/dataset_api.py
- python/hsml/engine/model_engine.py
JIRA Issue: -
Related PRs: -
```
```
> [HWORKS-2064] Auto-increment model export only looks at the model version folder, should also account for model version db metadata

- .github/workflows/python.yml
- python/hsfs/engine/spark.py
- python/hsfs/storage_connector.py
- python/tests/core/test_kafka_engine.py
- python/tests/engine/test_spark.py
- python/tests/test_storage_connector.py
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1667] Feature store client doesn't work on Databricks with BYOK setup

- python/hsfs/core/vector_server.py
…ject has no attribute 'writers_schema' (#553)"
This reverts commit 246da6611c9fd9a8870ab0f00dbe5c7e8b99c4ea.
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1749][UNDO] get_feature_vectors fails with 'DatumReader' object has no attribute 'writers_schema' 

- python/hsfs/core/vector_server.py
…ject has no attribute 'writers_schema' (#553)"
This reverts commit 246da6611c9fd9a8870ab0f00dbe5c7e8b99c4ea.
JIRA Issue: -
Related PRs: -
```
```
> [FSTORE-1749][UNDO] get_feature_vectors fails with 'DatumReader' object has no attribute 'writers_schema'

- python/hopsworks_common/core/job_api.py
This PR fixes an issue in which updating jobs fails with an AttributeError: 'JobApi' object has no attribute '_project_name'
**Root Cause:**
'_project_name' has been moved into the client class and is not part of JobAPI anymore.
**Fix Done:**
Use '_project_name' from the client class
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1755
Related PRs: -
```
```
> [FSTORE-1755] Updating jobs fails

- python/hsfs/core/vector_server.py
This PR cherry picks changes done by the PR https://github.com/logicalclocks/hopsworks-api/pull/593 to the 4.4 branch.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1796
Related PRs: -
```
```
> [FSTORE-1796][4.4] Cannot Retrieve Feature Vectors from Feature View with Only On-Demand Features and a Normal Label Feature

- python/hsfs/core/vector_server.py
This PR cherry picks changes done by the PR https://github.com/logicalclocks/hopsworks-api/pull/593 to the 4.3 branch.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1796
Related PRs: -
```
```
> [FSTORE-1796][4.3] Cannot Retrieve Feature Vectors from Feature View with Only On-Demand Features and a Normal Label Feature

- python/pyproject.toml
This PR cherry picks changes done in PR https://github.com/logicalclocks/hopsworks-api/pull/597 to the 4.4 branch
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1794
Related PRs: -
```
```
> [FSTORE-1794][4.4] Bump up fastavro to allow easy installation of hopsworks in Mac with apple silicon on Python 3.10

- python/pyproject.toml
This PR cherry picks changes done in PR https://github.com/logicalclocks/hopsworks-api/pull/597 to the 4.2 branch
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1794
Related PRs: -
```
```
> [FSTORE-1794][4.2] Bump up fastavro to allow easy installation of hopsworks in Mac with apple silicon on Python 3.10

- python/hsfs/engine/python.py
- python/tests/engine/test_python.py
JIRA Issue: -
Related PRs: -
```
```
> [HWORKS-1810] Add support for reading from Python from S3 compliant storages

- python/hsfs/core/vector_server.py
**Issue**:
When a feature group contains features with different data types, the get_feature_vector function returns a pandas DataFrame where all columns have the data type object.
**Root Cause**:
For single-row retrieval, the vector server was creating a DataFrame by treating the row as a column and then transposing it to form the final feature vector.
When pandas creates a DataFrame from a list, it automatically infers data types. However, since the vector server was constructing the DataFrame by considering feature vector as a single column, pandas could not correctly infer the data types. As a result, all columns defaulted to object.
**Fix**:
For single feature vector retrieval, the feature vector is now passed as a row when creating the DataFrame
JIRA Issue: …
> [FSTORE-1807] get_feature_vector does not return a pandas dataframe with correct Data Types
