python/hopsworks/client/exceptions.py
python/hopsworks/core/kafka_api.py
python/hopsworks/kafka_schema.py
python/hopsworks/kafka_topic.py
python/hopsworks/project.py

Support for kafka API

---

auto_doc.py
python/hopsworks/connection.py

Minor secrets documentation issues

---

python/hopsworks/core/opensearch_api.py

Fix opensearch host extraction

---

java/pom.xml
python/hopsworks/version.py
python/setup.py

**DO NOT MERGE UNTIL APP UPGRADE IS COMPLETE**

[CLOUD-658] Release version 3.4.2

---

python/hopsworks/__init__.py
python/hopsworks/client/__init__.py
python/hopsworks/connection.py

…s into account (#192)
* Cleanup client irrespective of whether connection was set
* Reset client in connection before initialising it

[FSTORE-1320] Fix hopsworks.login failing if client not properly initialized the first time

---

java/pom.xml
python/hopsworks/version.py
python/setup.py

Fixes https://hopsworks.atlassian.net/browse/CLOUD-718

[CLOUD-718] Release 3.7.0

---

python/hopsworks/client/external.py
python/hopsworks/core/project_api.py
python/hopsworks/core/variable_api.py

* Merge variable_api of hsfs
* Merge project_api of hsfs
* Ruff project_api
* Fix client/external so that Project API get_client works
That is, set _project_id.
* Fix Project API docs
* Add docs to variable_api
* Ruff client/external.py
* Refactor variable_api

[FSTORE-1454] Unify variable_api and project_api (#219)

---

python/tests/hopsworks/test_login.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1474] Disable hopsworks serverless login tests, to be moved to loadtests repo

---

python/hsfs/core/feature_group_engine.py
python/hsfs/core/feature_logging.py
python/hsfs/core/feature_view_engine.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_view.py
python/hsml/model.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1424] Feature logging for spark

---

python/hopsworks_common/client/base.py

JIRA Issue: -
Related PRs: -
```
```

Fix client.base so that hsml.util.get_hostname_replaced_url works again

---

locust_benchmark/common/hopsworks_client.py
python/hopsworks/connection.py
python/hopsworks_common/client/__init__.py
python/hopsworks_common/client/base.py
python/hopsworks_common/client/external.py
python/hopsworks_common/client/hopsworks.py
python/hsfs/connection.py
python/hsml/connection.py

JIRA Issue: [FSTORE-368](https://hopsworks.atlassian.net/browse/FSTORE-368)
Related PRs: -
```
```
[FSTORE-368]: https://hopsworks.atlassian.net/browse/FSTORE-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FSTORE-368] Remove code for secret store / parameter store from the hsfs APIs

---

utils/java/src/main/java/com/logicalclocks/utils/MainClass.java

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1048][APPEND] Add back System.exit(0) for fs jobs

---

python/hopsworks/__init__.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1484][APPEND] Set project in client when using hopsworks.login()

---

python/hopsworks/project.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1484][APPEND] download_certs() accepts no arguments anymore

---

python/hopsworks/__init__.py
python/hopsworks/client/exceptions.py
python/hopsworks/connection.py
python/hopsworks/project.py
python/hopsworks_common/client/__init__.py
python/hopsworks_common/client/base.py
python/hopsworks_common/client/exceptions.py
python/hopsworks_common/client/external.py
python/hopsworks_common/client/hopsworks.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1474] Add hostname verification parameter to hopsworks.login()

---

.gitignore
python/hopsworks_common/core/feature_store_activity_api.py
python/hopsworks_common/feature_store_activity.py
python/hopsworks_common/user.py
python/hsfs/core/feature_group_api.py
python/hsfs/core/feature_view_api.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1328][PREPARE] extra cluster endpoints + activity entities

---

python/hsml/core/serving_api.py

JIRA Issue: -
Related PRs: -
```
```

Fix istio client

---

python/hsml/core/serving_api.py

JIRA Issue: -
Related PRs: -
```
```

Fix usage of istio_get_instance

---

python/hopsworks_common/engine/environment_engine.py
python/hopsworks_common/library.py

JIRA Issue: -
Related PRs: -
```
```

Fix from_response_json calls in environment_engine

---

python/hopsworks_common/user.py

JIRA Issue: -
Related PRs: -
```
```

Fix User.__init__

---

python/hsfs/core/online_store_rest_client_api.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1500] Correctly set the encoder path if needed

---

python/hsfs/constructor/query.py
python/hsfs/core/feature_view_engine.py
python/hsfs/core/online_store_rest_client_api.py
python/hsfs/core/statistics_engine.py
python/hsfs/hopsworks_udf.py
python/tests/core/test_feature_view_engine.py
python/tests/core/test_statistics_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1477][APPEND] Continue removing hiveserver code paths

---

python/hopsworks/connection.py
python/hopsworks_common/job.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1506] Minor fixes for loadtests

---

python/hopsworks/connection.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1506][APPEND] Fix condition project

---

python/hsfs/core/deltastreamer_jobconf.py
python/hsfs/engine/python.py
python/hsfs/feature_group.py

…needed
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1497] Check delta config for key with null value + pop offline_backfill_every

---

python/hopsworks_common/core/opensearch.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1506] Avoid spamming opensearch log to users

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

Update docs of FeatureView.materialize_log

---

python/hopsworks/__init__.py

JIRA Issue: -
Related PRs: -
```
```

Remove redundant request of all projects in hopsworks.login

---

locust_benchmark/requirements.txt

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1517] update hopsworks in locust requirements

---

python/hopsworks/__init__.py

JIRA Issue: -
Related PRs: -
```
```

Make hopsworks.hsfs and hopsworks.hsml available

---

python/hsfs/core/online_store_sql_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1520] Similarity search workflow test never finishes

---

python/hopsworks_common/engine/execution_engine.py

JIRA Issue: -
Related PRs: -
```
```

Fix ExecutionEngine.wait_until_finished

---

python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1497][APPEND] Add _hr suffix to increase readability

---

python/hsml/core/dataset_api.py

JIRA Issue: -
Related PRs: -
```
```

Change DatasetApi._archive so that False is returned if timeout is exceeded

---

README.md
python/hopsworks/__init__.py

Also fix _prompt_project.
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1529] Add get_sdk_info from hsfs to hopsworks init

---

python/hopsworks_common/connection.py

JIRA Issue: -
Related PRs: -
```
```

Only load hsml resources if data science profile

---

python/hopsworks_common/connection.py
python/hopsworks_common/core/variable_api.py

JIRA Issue: -
Related PRs: -
```
```

[#312][Append] Fix enable_data_science_profile check

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

Fix kafka import in feature_group

---

python/hsfs/core/feature_view_api.py

JIRA Issue: -
Related PRs: -
```
```

Fix feature_view_api, so that it always uses the current client

---

python/hsfs/core/feature_view_engine.py
python/hsfs/core/kafka_engine.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_logger.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1509] Async feature logging

---

python/hopsworks_common/client/__init__.py
python/hopsworks_common/client/external.py
python/hopsworks_common/connection.py
python/hopsworks_common/project.py
python/hsfs/engine/__init__.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1476][APPEND] Fix reconnection error

---

python/hsfs/core/feature_view_engine.py

JIRA Issue: -
Related PRs: -
```
```

[APPEND][FSTORE-1509] Fix online model logging

---

python/hsfs/core/feature_view_engine.py
python/hsfs/core/online_store_sql_engine.py
python/hsfs/engine/python.py
python/hsfs/feature_logger.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1538] refactor closing connection pool

---

python/hopsworks_common/client/exceptions.py
python/tests/test_feature_group.py

JIRA Issue: -
Related PRs: -
```
```

Fix that error_code was not in RestAPIError

---

python/hopsworks_common/connection.py

JIRA Issue: -
Related PRs: -
```
```

Remove login warnings from Connection

---

python/hopsworks_common/project.py
python/hsml/core/serving_api.py
python/hsml/deployment.py
python/hsml/predictor.py
python/tests/fixtures/predictor_fixtures.json

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1421] Add option to specify kubernetes namespace at project creation

---

java/pom.xml
python/hopsworks/version.py
python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.8.0-RC2 with HSFS 3.8.0-RC3

---

python/hsml/predictor.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1421][APPEND] should be camelCase in Predictor.to_dict()

---

python/tests/fixtures/predictor_fixtures.json

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1639] misc environment was renamed to pandas

---

python/hsfs/core/delta_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1327] Activity UI doesn't correctly report Delta commit activities

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksHttpClient.java
java/hsfs/src/test/java/com/logicalclocks/hsfs/metadata/TestHopsworksClient.java

JIRA Issue: -
Related PRs: -
```
```

NullPointerException in HopsworksHttpClient

---

python/hsfs/core/delta_engine.py
python/hsfs/core/feature_group_engine.py
python/hsfs/feature_group.py
python/tests/core/test_feature_group_engine.py
utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1537][APPEND] Managed feature group delta vacuum

---

java/beam/src/main/java/com/logicalclocks/hsfs/beam/StreamFeatureGroup.java
java/flink/src/main/java/com/logicalclocks/hsfs/flink/StreamFeatureGroup.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/FeatureGroupBase.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupUtils.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/ExternalFeatureGroup.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/FeatureGroup.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/StreamFeatureGroup.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestFeatureGroup.java
python/hsfs/constructor/fs_query.py
python/hsfs/core/arrow_flight_client.py
python/hsfs/core/delta_engine.py
python/hsfs/core/feature_group_engine.py
python/hsfs/core/hudi_engine.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/storage_connector.py
python/pyproject.toml
python/tests/core/test_arrow_flight_client.py
python/tests/core/test_feature_group_engine.py
python/tests/engine/test_spark.py
python/tests/test_feature_group.py
utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1556] Managed feature group

---

python/hsfs/storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[APPEND][FSTORE-1536] Refetch s3 credential

---

python/hsfs/storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[APPEND][FSTORE-1536] Add S3 endpoint

---

python/hopsworks_common/constants.py
python/hsml/deployment.py
python/hsml/engine/model_engine.py
python/hsml/engine/serving_engine.py
python/hsml/model.py
python/hsml/predictor.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1037] Download artifact files from deployment

---

python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

Fix typo in hsfs/engine/python.py

---

.github/workflows/python.yml

JIRA Issue: -
Related PRs: -
```
```

Fix Spark Java endpoint

---

python/hsml/core/hdfs_api.py
python/hsml/engine/local_engine.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1037][Append] Add HdfsApi with pyarrow-hdfs client

---

python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1537][APPEND] External feature group fix for getting features from dataset

---

python/hsml/deployment.py
python/hsml/engine/model_engine.py
python/hsml/engine/serving_engine.py
python/hsml/model.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1737] Support local_path param in download methods

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Prepare for 4.2.0-SNAPSHOT development

---

python/hopsworks_common/client/online_store_rest_client.py
python/hopsworks_common/connection.py
python/hopsworks_common/project.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py
python/hsml/core/dataset_api.py

JIRA Issue: -
Related PRs: -
```
```

Fix imports in API documentation

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks/__init__.py
python/hopsworks_common/connection.py
python/hopsworks_common/project.py
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Add engine parameter to hopsworks.login

---

utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1564][APPEND] Delta deltastreamer dont write to online store

---

java/pom.xml
python/hopsworks/version.py
python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1564] Bump HSFS requirements in hopsworks-api

---

python/hopsworks/__init__.py
python/hopsworks_common/connection.py
python/hopsworks_common/project.py

JIRA Issue: -
Related PRs: -
```
```

Add engine parameter to hopsworks.login (main)

---

locust_benchmark/README.md
locust_benchmark/common/hopsworks_client.py
locust_benchmark/hopsworks_config.json

JIRA Issue: -
Related PRs: -
```
```

Add tablespace support to locust

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

Close ``` to fix delta vacuum scroll in docs.

---

python/hsml/engine/model_engine.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1802] Exporting model on windows with directories in the model directory creates invalid upload path

---

python/hsfs/engine/spark.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1604] Add option to avoid setting s3a global options

---

python/hopsworks_common/core/dataset_api.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1442] Extend the dataset upload method to be able to upload a directory using the REST API

---

python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1615] Inserting into streaming FG fails after cluster upgrade

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.1.0

---

python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1624] Fix confluent kafka logging

---

java/flink/src/main/java/com/logicalclocks/hsfs/flink/HopsworksConnection.java
java/flink/src/main/java/com/logicalclocks/hsfs/flink/engine/FlinkEngine.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksClient.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1619] Update Flink certificate management

---

utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1627] Don't fail Delta delta-streamer on data loss

---

python/hopsworks/__init__.py
python/hopsworks_common/connection.py
python/hopsworks_common/project.py

JIRA Issue: -
Related PRs: -
```
```

Add engine parameter to hopsworks.login (4.1)

---

python/hsfs/feature_group.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py

JIRA Issue: -
Related PRs: -
```
```

Fix link to job configuration documentation (#425)

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/connection.py
python/hopsworks_common/version.py
utils/java/pom.xml

[FSTORE-1633] Fix engine choice in case of connection to serverless (4.1)

---

java/pom.xml
java/spark/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1628] Update deequ for spark 3.5 support

---

python/hopsworks/__init__.py
python/hopsworks_common/client/external.py
python/hopsworks_common/connection.py
python/hsfs/engine/__init__.py
python/hsfs/engine/spark_no_metastore.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1626] Spark client without hopsfs

---

python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1893] Upgrade confluent-kafka to 2.6.1

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 4.1.4

---

python/hsfs/storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1679] Remove confusing log message

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1681] Add support for JSON as file format for training datasets

---

python/hopsworks_common/core/git_api.py
python/hopsworks_common/git_repo.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-314] Add git fetch and reset

---

python/hsfs/core/arrow_flight_client.py

JIRA Issue: -
Related PRs: -
```
```

Fix backwards compatibility of the arrowflight client

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bumping Python Version to 4.1.7

---

python/pyproject.toml

This PR adds the packaging library to the dependencies. Which is required because of PR : https://github.com/logicalclocks/hopsworks-api/pull/473
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1672][4.1][APPEND-2] Add missing packaging dependency

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bumping version to 4.1.8

---

python/hsfs/core/spine_group_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1688] Spine feature group does not have `foreign_key` attribute

---

python/hopsworks_common/core/dataset_api.py

JIRA Issue: -
Related PRs: -
```
```

Fix blocking zip/unzip

---

docs/templates/model-registry/model_api.md
docs/templates/model-serving/predictor_state_api.md
python/auto_doc.py
python/hsml/deployment.py
python/hsml/model.py
python/hsml/model_serving.py
python/hsml/predictor.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1885] Improve vLLM-related docs

---

python/hsfs/core/feature_view_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1523][APPEND] get_training_dataset_schema should not pass td version

---

python/hsfs/constructor/query.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1652] generate and add prefix automatically to joins if there is name clash

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Prepare for 4.3.0-SNAPSHOT development

---

python/hopsworks_common/util.py

Cherry pick changes from PR : https://github.com/logicalclocks/hopsworks-api/pull/501
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1656][APPEND][4.2] Fetching feature vectors in the predictor file of a deployment fails with event loop is already running error

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.2.0.RC1

---

python/hopsworks_common/core/dataset_api.py
python/hsml/engine/model_engine.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2064] Auto-increment model export only looks at the model version folder, should also account for model version db metadata (#503)

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bumping up client version to 4.2.0-RC2

---

python/hopsworks/__init__.py
python/hopsworks_common/core/project_api.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2078] python client login on serverless should exclude projects not owner by the user

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bumping up client version to 4.2.0-RC3

---

python/hsfs/constructor/query.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1704] Improve error message when read from embedding fg

---

.github/ci.Jenkinsfile
.github/workflow_inputs.sh
python/hsfs/core/online_store_rest_client_engine.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1552] Decode rdrs date and binary features

---

python/hopsworks_common/core/secret_api.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2099][APPEND] Fix secrets api docstring

---

python/auto_doc.py
python/hopsworks_common/core/dataset_api.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2100] DatasetAPI docs should hide newly added internal functions 

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bump to Hopsworks API to 4.2.0 rc4

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.2.0

---

python/hsml/model.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1719] Add the "add_tag" method; Deprecate "set_tag"

---

python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1177] Pandas 2.2.x support

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1727] for ExternalFeatureGroup omit partition key in select_features method

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.2.1

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
python/hsfs/core/online_store_rest_client_engine.py
utils/java/pom.xml

* decode rdrs features
* fix style
* add doc string
* reformat
* Fix the jenkins CI
* Why jenkins can't find the right ref for loadtest
* Close the extra PR
* Allow to target different loadtest branch workflow dispatch
* Mostly just triggering again
* Just trigger
* Just trigger more
* Trigger
* Test forcing to use the workflow from the loadtest branch
* add echo, mostly trigger
* Add some info
* Don't use a fixed base ref for loadtest
---------
JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1552] Decode rdrs date and binary features 4.2

---

python/hsfs/core/schema_validation.py
python/tests/test_schema_validator.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-17080][APPEND] pandas string types checks

---

python/hopsworks_common/core/git_api.py
python/hopsworks_common/core/git_provider_api.py
python/hopsworks_common/git_provider.py

* [HWORKS-2144] Add hostname to git providers
* Add host to print
* get_provider should not return list
JIRA Issue: -
Related PRs: -
```
```
[HWORKS-2144]: https://hopsworks.atlassian.net/browse/HWORKS-2144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HWORKS-2144] Add hostname to git providers (#543)

---

python/hsfs/core/arrow_flight_client.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1735] ExternalFeatureGroup's query that reads features from the source table should select all its features with original names

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.2.3

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.2.4

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Prepare for 4.4.0-SNAPSHOT development

---

python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/storage_connector.py
python/tests/test_feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1741] Data sources workflow tests and improvements

---

python/hopsworks_common/core/job_api.py

This PR cherry picks changes done in PR : https://github.com/logicalclocks/hopsworks-api/pull/562 to the 4.2 branch
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1755
Related PRs: -
```
```

[FSTORE-1755][4.2] Updating jobs fails 

---

python/hopsworks_common/core/job_api.py

This PR cherry picks changes done in PR : https://github.com/logicalclocks/hopsworks-api/pull/562 to the 4.3 branch
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1755
Related PRs: -
```
```

[FSTORE-1755][4.3] Updating jobs fails

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.2.5

---

java/pom.xml
python/hopsworks/version.py
python/pyproject.toml

…ns jobs
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1732] Handle duplicated events for Delta Table materializations jobs

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.3.0

---

python/hsfs/feature_store.py

JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1763
Related PRs: -
```
```

[FSTORE-1763] Make get_feature_groups return all FGs if there is no name

---

python/hopsworks_common/core/dataset_api.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2196] It should be possible to upload and download empty files using the python client

---

python/hopsworks_common/core/dataset_api.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2196] It should be possible to upload and download empty files using the python client (#574)

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.3.1

---

.github/workflows/mkdocs-release.yml
mkdocs.yml

JIRA Issue: -
Related PRs: -
```
```

Fstore 1771 4.2

---

docs/templates/api/online_ingestion.md
docs/templates/api/online_ingestion_result.md
mkdocs.yml
python/auto_doc.py
python/hsfs/core/online_ingestion.py
python/hsfs/core/online_ingestion_api.py
python/hsfs/core/online_ingestion_result.py
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1780] onlinefs observability docs

---

.github/workflows/mkdocs-release.yml

JIRA Issue: -
Related PRs: -
```
```

Remove latest tag from 4.3 branch

---

python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1794] Bump up fastavro to allow easy installation of hopsworks in Mac with apple silicon on Python 3.10

---

python/hsfs/core/feature_group_engine.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py

Reverts logicalclocks/hopsworks-api#584

Revert "[FSTORE-1731] Time-to-Live (TTL) for Feature Group"

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.2.7

---

python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2266] Upgrade minimum arrow version

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/FeatureGroupCommit.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/HudiEngine.java
python/hsfs/core/hudi_engine.py
python/hsfs/feature_group_commit.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2183] Calculate hudi table size on each commit

---

python/hopsworks_common/client/online_store_rest_client.py
python/hsfs/core/online_store_rest_client_api.py
python/hsfs/core/online_store_rest_client_engine.py
python/hsfs/core/online_store_sql_engine.py
python/hsfs/core/vector_server.py

The PR fixes an issue in which a increase in latency was observed during fetching feature vectors.
**Root Cause:**
The function [handle_rdrs_feature_store_response](https://github.com/logicalclocks/feature-store-api/blob/master/python/hsfs/core/online_store_rest_client_api.py#L160) was taking a CPU because the [logger message](https://github.com/logicalclocks/feature-store-api/blob/master/python/hsfs/core/online_store_rest_client_api.py#L180) was getting created even if the message was not printed.
**Fix Done:**
Add if conditions to check the logger messages before it is printed.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1793
Related PRs: -
```
```

[FSTORE-1793] Logger messages increasing latency for during fetching feature vectors.

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/FeatureViewBase.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/engine/VectorServer.java
java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1791] Add method to return strongly typed object from feature vector in java

---

python/hsfs/engine/spark.py
python/hsfs/storage_connector.py
python/tests/test_storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1805] Using multiple Kafka connectors from the same Spark session doens't work

---

python/hsfs/core/feature_group_engine.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1731] Time-to-Live (TTL) for Feature Group

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
python/hsfs/engine/spark.py
python/tests/engine/test_spark.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Fix Kafka connector when reading data for BYOK

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 4.3.2

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release Hopsworks 4.4.1

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release Hopsworks 4.2.8

---

python/hsfs/storage_connector.py
python/tests/test_storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1805][APPEND] allow multiple calls for kafka connector spark_options

---

java/flink/src/main/java/com/logicalclocks/hsfs/flink/engine/FlinkEngine.java
java/flink/src/main/java/com/logicalclocks/hsfs/flink/engine/KafkaRecordSerializer.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1829] Flink applications are not recoverable

---

.github/workflows/python.yml
java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
python/hsfs/core/arrow_flight_client.py
python/tests/core/test_arrow_flight_client.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release Hopsworks 4.4.2

---

.github/workflows/java.yml
.github/workflows/mkdocs-main.yml
.github/workflows/mkdocs-release.yml
CONTRIBUTING.md
java/pom.xml
java/spark/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[HOPSFS-282] Bump slf4j in hsfs-parent to match hopsfs 3.2.0.17-EE-RC3

---

python/auto_doc.py
python/hopsworks/mcp/tools/dataset.py
python/hopsworks_common/core/dataset.py
python/hopsworks_common/core/dataset_api.py
python/hopsworks_common/core/inode.py
python/hopsworks_common/util.py
python/hsfs/engine/python.py
python/hsml/engine/model_engine.py
python/hsml/engine/serving_engine.py
python/tests/core/test_arrow_flight_client.py
python/tests/engine/test_python.py
python/tests/engine/test_python_reader.py
python/tests/fixtures/inode_fixtures.json

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2317] Add dataset api list function

---

python/hsfs/core/vector_server.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py
python/tests/client/test_base_client.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1857] Enable get feature vector for spine group

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hopsworks_common/version.py
python/hsfs/core/vector_server.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py
utils/java/pom.xml

* Enable get feature vector for spine group
* style fix
* style fix
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1857] Enable get feature vector for spine group v4.5 (#660)

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/auto_doc.py
python/hopsworks_common/core/dataset.py
python/hopsworks_common/core/dataset_api.py
python/hopsworks_common/core/inode.py
python/hopsworks_common/util.py
python/hopsworks_common/version.py
python/hsfs/engine/python.py
python/hsml/engine/model_engine.py
python/hsml/engine/serving_engine.py
python/tests/core/test_arrow_flight_client.py
python/tests/engine/test_python.py
python/tests/engine/test_python_reader.py
python/tests/fixtures/inode_fixtures.json
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-2317] Add dataset api list function (#643)

---

python/hsfs/core/delta_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1617][APPEND] Integrate delta-rs HopsFS writer to hsfs python client
